### ISSUE TITLE
Quantification period, detail page

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise_frontend#10]
@kristoferlund commented on [Tue Oct 12 2021](https://github.com/CommonsBuild/coordination/issues/1011)

## Layout
![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/360245d9-6b5d-4e03-9722-3fd5123aeb5a)

## Edit period name
![image.png](https://images.zenhubusercontent.com/5fdba670baa205320c5a291e/7a9768f8-0fe6-4d60-ab7b-02d47d5e22bb)

**Comment by Big-Gray-Al** [comment]
Most recent  [commit: add reset on click outside](https://github.com/CommonsBuild/praise_frontend/commit/6c4f5b5c5f0c1e2bef1d0c9c65b14e9e3a6b9a86)  completes this feature set with the exception of automatic re-rendering.  I will probably need to review the state management with @kristoferlund to resolve.

Branch: https://github.com/CommonsBuild/praise_frontend/tree/feature/PRFE_0010-quantification-period-show/src/pages
