### ISSUE TITLE
can mark praise duplicate of itself

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/praise_frontend#108]
using the ID system it is possible for a quantifier to mark a praise as a duplicate of itself - this shouldn't be possible and can make some weird calculations/errors in the system. 

![image](https://user-images.githubusercontent.com/67759413/149517837-fc4a8a3a-b2d9-4022-80bc-627be3116b04.png)

**Comment by kristoferlund** [comment]
Done.
