### ISSUE TITLE
allow admin to view quantifiers quantification

### ISSUE THREAD

**Issue by divine-comedian** [CommonsBuild/praise_frontend#140]
it would be useful for admins during and after quantification periods to be able to check on the work of quantifiers. this will be helpful for reward system admins to guide quantifiers if they have any questions or clarifications regarding praise

**Comment by kristoferlund** [comment]
Quantifiers are now clickable on the period details page, taking you to a quantifer detail page like this:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/9698363/190211135-20824fbd-afd6-4aaa-bb2d-0947bfa1faff.png">

This page is accessible during quantification as well for admins that want to check in on quantifiers. 

Closing issue.
