### ISSUE TITLE
Default values assigned to sliders

### ISSUE THREAD

**Issue by PhilH** [CommonsBuild/praise_frontend#143]
I just opened a new receiver page and there are values already set on both sliders, I'm pretty sure I haven't set (nor seen) these one before. It's unsettling.
![image](https://user-images.githubusercontent.com/53337/150550690-d26249d9-c6b9-40df-9203-26c17f3898fa.png)

**Comment by PhilH** [comment]
Actually, I understand the pattern now. When accessing a new receiver with "next" link in the bottom left area of the page, the sliders are set with the values of the previous page.

**Comment by kristoferlund** [comment]
Thanks @PhilH! Yes, there was an UI bug that occured when navigating betweeen pages. Now fixed.
