### ISSUE TITLE
Database user / password

### ISSUE THREAD

**Issue by kristoferlund** [CommonsBuild/praise_frontend#148]

**Comment by nebs-dev** [comment]
Steps to set up database authentication:

- Login to the mongo - `mongo`
- Switch to the admin database - `use admin`
- You need to create a user with the userAdminAnyDatabase role, which grants the privilege to create other users on any existing database:
```db.createUser(
  {
    user: "superadmin",
    pwd: "superadmin123",
    roles: [ { role: "userAdminAnyDatabase", db: "admin" } ]
  }
)```
- Enable authentication in mongod configuration file:
```security:
    authorization: "enabled"```
- Restart mongo service
- Connect and authenticate as the user administrator:
`mongo`
`db.auth("superadmin", "superadmin123")`
- Switch to the praise database - `use praise_db`
- Create admin user for that database:
```db.createUser(
  {
    user: "praiseUser",
    pwd: "praiseUser123",
    roles: [ { role: "readWrite", db: "praise_db" } ]
  }
)```

**Comment by kristoferlund** [comment]
How does this work when running mongodb in Docker?
- Enable authentication in mongod configuration file `/etc/mongod.conf`:
`security: authorization: "enabled"`

**Comment by nebs-dev** [comment]
We need to access mongo docker container and do the same thing that i explained there

**Comment by kristoferlund** [comment]
https://www.mrnakumar.com/docker_mongo_security/

https://stackoverflow.com/questions/34559557/how-to-enable-authentication-on-mongodb-through-docker

Use .env file
`--env-file in docker-compose`
https://dimmaski.com/env-files-docker/
