### ISSUE TITLE
Invalid asset path crashes entire front-end

### ISSUE THREAD

**Issue by Big-Gray-Al** [CommonsBuild/praise_frontend#16]
Assets like images & icons need an ErrorHandling wrapper, see here:
`https://reactjs.org/docs/error-boundaries.html`

## To reproduce:
For example, If i am logged via the dev server and and looking at an unrelated page such as:
`http://localhost:3000/periods`

Then change one character of the path to MetamaskIcon (located at line 5 of `Login.tsx`) and save

## What happens
An app-wide crash due to `Compilation Error`

## What I expect
  A console error only on pages where that icon is expected to be rendered or some other fallback

**Comment by kristoferlund** [comment]
I do believe compile time errors are not caught by the error boundaries but indeed will cause the whole build to fail.
