### ISSUE TITLE
'Create Period' button does not reset after submitting a period 

### ISSUE THREAD

**Issue by Big-Gray-Al** [CommonsBuild/praise_frontend#18]
Steps to recreate:

1- launch backend and frontend, 
2- visit frontend and login with admin priviledges
3- visit http://localhost:3000/periods
4- add valid inputs and click 'Create Period', notice that button changes to 'Period Created' get redirected back to http://localhost:3000/periods
5- note that the button still says 'Period Created'
6- Add valid inputs and click  'Period Created', form submission is still successful

Expected behaviour. Button already reverted to 'Create Period' if you revisit the page

**Comment by kristoferlund** [comment]
Good catch, I'll fix it.

**Comment by kristoferlund** [comment]
Fixed.
