### ISSUE TITLE
Choose between single-server or multi-server deployment

### ISSUE THREAD

**Issue by Big-Gray-Al** [CommonsBuild/praise_frontend#24]
Asked via discord (praise-dev):
 - is it preferrable to deploy FE & BE together or separately?

**Comment by Big-Gray-Al** [comment]
Kristof has mentioned Discourse as a good benchmark for us to aim at in terms of packaging/distribution.  
In their install guide, they have both single server and multi-server docker options which probably evolved over time.
https://github.com/discourse/discourse/blob/main/docs/INSTALL.md

**Comment by graial** [comment]
while a multi-docker setup is under development, the current setup is split by the repos: 
 - backend (with hosted db)
 - frontend
