### ISSUE TITLE
Input csv of praise into db

### ISSUE THREAD

**Issue by Big-Gray-Al** [CommonsBuild/praise_frontend#25]
- we input all accumulated praise into the system (csv? or api?)

This is the sheet:

https://docs.google.com/spreadsheets/d/1d7KVvAUlWb2yZPDTMttr1gEHzod6RKOiheGk-FX0BqE/edit#gid=0

**Comment by graial** [comment]
Initial implementation via 
 - parser written in ruby 
 - submission to local or staging via cypress
https://github.com/CommonsBuild/praise_frontend/tree/praise_data_script
