### ISSUE TITLE
Confirm of using Ubuntu as OS?

### ISSUE THREAD

**Issue by Big-Gray-Al** [CommonsBuild/praise_frontend#29]
Ubuntu is the obvious default OS due to widespread familiarity. 
Is there any reason to consider an alternative OS for the servers?

**Comment by kristoferlund** [comment]
Moved question to Notion doc for the deployment Epic (under Open Questions): https://www.notion.so/fmckl/MVP-deployment-and-hosting-2c02e0fb6f4c4b1cb8e2bcc73518e7eb
