### ISSUE TITLE
Login button fails silently with TypeError if pressed from browser with no MetaMask

### ISSUE THREAD

**Issue by Big-Gray-Al** [CommonsBuild/praise_frontend#5]
The error reported in the browser console

> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getSigner')
>     at signLoginMessage (Login.tsx:74)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
>     at invokeGuardedCallback (react-dom.development.js:4056)
>     at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070)
>     at executeDispatch (react-dom.development.js:8243)
>     at processDispatchQueueItemsInOrder (react-dom.development.js:8275)
>     at processDispatchQueue (react-dom.development.js:8288)
>     at dispatchEventsForPlugins (react-dom.development.js:8299)
>     at react-dom.development.js:8508
>     at batchedEventUpdates$1 (react-dom.development.js:22396)
>     at batchedEventUpdates (react-dom.development.js:3745)
>     at dispatchEventForPluginEventSystem (react-dom.development.js:8507)
>     at attemptToDispatchEvent (react-dom.development.js:6005)
>     at dispatchEvent (react-dom.development.js:5924)
>     at unstable_runWithPriority (scheduler.development.js:468)
>     at runWithPriority$1 (react-dom.development.js:11276)
>     at discreteUpdates$1 (react-dom.development.js:22413)
>     at discreteUpdates (react-dom.development.js:3756)
>     at dispatchDiscreteEvent (react-dom.development.js:5889)

**Comment by kristoferlund** [comment]
Added better error handling, [see commit](https://github.com/CommonsBuild/praise_frontend/commit/21fa257a4cc73198e56d7726564d44408502476d) for details.
![image](https://user-images.githubusercontent.com/9698363/139558081-187bce7c-4653-4144-be55-718396d8345e.png)
