### ISSUE TITLE
 Login button failovers to DevMode error page with TypeError if pressed from browser with MetaMask

### ISSUE THREAD

**Issue by Big-Gray-Al** [CommonsBuild/praise_frontend#9]
My wallet public key is showing up correctly in the browser.  When I try to click login, it fails over to the following DevMode error page

> Unhandled Rejection (TypeError): value is undefined
> isHexable
> /home/al/external_projects/commonsstack/src.ts/index.ts:55
> 
>   52 | }
>   53 | export class TransactionOrderForkEvent extends ForkEvent {
>   54 |     constructor(beforeHash, afterHash, expiry) {
> > 55 |         if (!isHexString(beforeHash, 32)) {
>   56 |             logger.throwArgumentError("invalid transaction hash", "beforeHash", beforeHash);
>   57 |         }
>   58 |         if (!isHexString(afterHash, 32)) {
> 
> hexlify
> /home/al/external_projects/commonsstack/src.ts/index.ts:225
> signMessage/<
> /home/al/external_projects/commonsstack/src.ts/json-rpc-provider.ts:252
> 
>   249 | }
>   250 | unlock(password) {
>   251 |     return __awaiter(this, void 0, void 0, function* () {
> > 252 |         const provider = this.provider;
>       | ^  253 |         const address = yield this.getAddress();
>   254 |         return provider.send("personal_unlockAccount", [address.toLowerCase(), password, null]);
>   255 |     });

Error report in browser console:

>     Uncaught (in promise) TypeError: value is undefined
>     isHexable index.ts:55
>     hexlify index.ts:225
>     signMessage json-rpc-provider.ts:252
>     fulfilled vendors~main.chunk.js:9129
>     promise callback*step vendors~main.chunk.js:9144
>     node_modules vendors~main.chunk.js:9147
>     node_modules vendors~main.chunk.js:9126
>     signMessage vendors~main.chunk.js:9415
>     signLoginMessage Login.tsx:74
>     React 14
>     unstable_runWithPriority scheduler.development.js:468
>     React 15
>     tsx index.tsx:33
>     tsx main.chunk.js:2359
>     Webpack 7

**Comment by kristoferlund** [comment]
Cause of error was old backend running. Even so, added more graceful error handling if similar error would occuer going forward. 

![Skärmavbild 2021-10-28 kl  14 34 46](https://user-images.githubusercontent.com/9698363/139557531-1f3ddaeb-0a32-4e9b-8260-c659f906d635.png)
